/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GameRouteImport } from './routes/game'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as LobbiesIndexRouteImport } from './routes/lobbies.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as LobbiesIdRouteImport } from './routes/lobbies.$id'
import { Route as ForumNewRouteImport } from './routes/forum.new'
import { Route as ForumIdRouteImport } from './routes/forum.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbiesIndexRoute = LobbiesIndexRouteImport.update({
  id: '/lobbies/',
  path: '/lobbies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbiesIdRoute = LobbiesIdRouteImport.update({
  id: '/lobbies/$id',
  path: '/lobbies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumNewRoute = ForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/lobbies/$id': typeof LobbiesIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/result/$id': typeof ResultIdRoute
  '/forum/': typeof ForumIndexRoute
  '/lobbies/': typeof LobbiesIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/lobbies/$id': typeof LobbiesIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/result/$id': typeof ResultIdRoute
  '/forum': typeof ForumIndexRoute
  '/lobbies': typeof LobbiesIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/lobbies/$id': typeof LobbiesIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/result/$id': typeof ResultIdRoute
  '/forum/': typeof ForumIndexRoute
  '/lobbies/': typeof LobbiesIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gallery'
    | '/game'
    | '/login'
    | '/notifications'
    | '/play'
    | '/profile'
    | '/signup'
    | '/upload'
    | '/forum/$id'
    | '/forum/new'
    | '/lobbies/$id'
    | '/messages/$id'
    | '/result/$id'
    | '/forum/'
    | '/lobbies/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gallery'
    | '/game'
    | '/login'
    | '/notifications'
    | '/play'
    | '/profile'
    | '/signup'
    | '/upload'
    | '/forum/$id'
    | '/forum/new'
    | '/lobbies/$id'
    | '/messages/$id'
    | '/result/$id'
    | '/forum'
    | '/lobbies'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gallery'
    | '/game'
    | '/login'
    | '/notifications'
    | '/play'
    | '/profile'
    | '/signup'
    | '/upload'
    | '/forum/$id'
    | '/forum/new'
    | '/lobbies/$id'
    | '/messages/$id'
    | '/result/$id'
    | '/forum/'
    | '/lobbies/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  GameRoute: typeof GameRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  ForumIdRoute: typeof ForumIdRoute
  ForumNewRoute: typeof ForumNewRoute
  LobbiesIdRoute: typeof LobbiesIdRoute
  MessagesIdRoute: typeof MessagesIdRoute
  ResultIdRoute: typeof ResultIdRoute
  ForumIndexRoute: typeof ForumIndexRoute
  LobbiesIndexRoute: typeof LobbiesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbies/': {
      id: '/lobbies/'
      path: '/lobbies'
      fullPath: '/lobbies/'
      preLoaderRoute: typeof LobbiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobbies/$id': {
      id: '/lobbies/$id'
      path: '/lobbies/$id'
      fullPath: '/lobbies/$id'
      preLoaderRoute: typeof LobbiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/new': {
      id: '/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof ForumNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/forum/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  GameRoute: GameRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  ForumIdRoute: ForumIdRoute,
  ForumNewRoute: ForumNewRoute,
  LobbiesIdRoute: LobbiesIdRoute,
  MessagesIdRoute: MessagesIdRoute,
  ResultIdRoute: ResultIdRoute,
  ForumIndexRoute: ForumIndexRoute,
  LobbiesIndexRoute: LobbiesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
